### ISSUE TITLE
Migrator unable to download dependency

### ISSUE THREAD

**Issue by the-brownstone** [spring-projects-experimental/spring-boot-migrator#758]
**Describe the bug**
When I run a recipe (e.g., apply boot-2.7-3.0-dependency-version-update), I am getting the error Unable to download dependency io.zipkin.brave:brave-bom:5.14.1 from the following repositories :
  - file:/C:/Users/user-name/.m2/repository/
  - https://repo.maven.apache.org/maven2

**SBM Version**
v0.13.0

**SBM Application**
Spring boot migrator

**To Reproduce**
1. Run Spring Boot Migrator: java -jar spring-boot-migrator.jar
2. Scan application: scan <app-folder>
3. Choose one of the recipes to run: apply boot-2.7-3.0-dependency-version-update
4. Error appears

**Expected behavior**
Spring Boot Migrator properly runs the recipe

**Screenshots**
```
Applying recipe 'boot-2.7-3.0-dependency-version-update'
..   Check if the application adheres to preconditions.No dependency to Google AppEngine's AppEngineDriver found.
[ok] Check if the application adheres to preconditions.
[ok] Upgrade Spring Cloud Dependencies
 [X] Add Spring Milestone Repository and bump SpringBoot to 3.0.0
Action [OpenRewriteDeclarativeRecipeAdapter] 'Add Spring Milestone Repository and bump SpringBoot to 3.0.0' failed: java.lang.RuntimeException: org.openrewrite.UncaughtVisitorException: org.openrewrite.maven.internal.MavenDownloadingException: Unable to download dependency io.zipkin.brave:brave-bom:5.14.1 from the following repositories :
  - file:/C:/Users/2002434/.m2/repository/
  - https://repo.maven.apache.org/maven2
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
```

**Stacktrace**
```
Caused by: org.openrewrite.maven.internal.MavenDownloadingException: Unable to download dependency io.zipkin.brave:brave-bom:5.14.1 from the following repositories :
  - file:/C:/Users/xxx/.m2/repository/
  - https://repo.maven.apache.org/maven2
        at org.openrewrite.maven.internal.MavenPomDownloader.download(MavenPomDownloader.java:311)
        at org.openrewrite.maven.tree.ResolvedPom$Resolver.mergeDependencyManagement(ResolvedPom.java:469)
        at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentDependenciesRecursively(ResolvedPom.java:376)
        at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentsRecursively(ResolvedPom.java:328)
        at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolve(ResolvedPom.java:297)
        at org.openrewrite.maven.tree.ResolvedPom.resolve(ResolvedPom.java:142)
        at org.openrewrite.maven.tree.Pom.resolve(Pom.java:96)
        at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject.buildDependencyMap(UpgradeUnmanagedSpringProject.java:185)
        at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject.getDependenciesMap(UpgradeUnmanagedSpringProject.java:110)
        at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.mayBeUpdateVersion(UpgradeUnmanagedSpringProject.java:138)
        at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:131)
        at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:116)
        at org.openrewrite.xml.tree.Xml$Tag.acceptXml(Xml.java:448)
        at org.openrewrite.xml.tree.Xml.accept(Xml.java:55)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
        ... 40 more
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
- We are behind corporate firewall and can't directly download artifacts from maven central. 
- We have an internal Artifactory repository (we are not connecting through proxy)
- In my .m2/settings.xml, 2 custom repositories are defined:
```xml
<profiles>
		<profile>
			<repositories>
				<repository>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
					<id>release</id>
					<name>maven-release</name>
					<url>https://internal-artifactory-url/artifactory/maven-release</url>
				</repository>
				<repository>
					<snapshots />
					<id>snapshots</id>
					<name>maven-snapshot</name>
					<url>https://internal-artifactory-url/artifactory/maven-snapshot</url>
				</repository>
			</repositories>
                        <pluginRepositories>...</pluginRepositories>
			<id>artifactory</id>
		</profile>
	</profiles>
	<activeProfiles>
		<activeProfile>artifactory</activeProfile>
	</activeProfiles>
```
- I've also tried adding the repositories to my project's POM file
- Neither repos defined in settings.xml nor in pom.xml are being used based on the error message.

**Comment by the-brownstone** [comment]
This is fixed in latest main branch

**Comment by InfoSec812** [comment]
I am still seeing this issue (Nexus repo in my case) with the Aug 5 release (0.15.0). 

```
<settings>
  <mirrors>
    <mirror>
      <!--This sends everything else to /public -->
      <id>nexus</id>
      <mirrorOf>*</mirrorOf>
      <url>http://nexus3.cpl:9081/repository/maven-public/</url>
    </mirror>
  </mirrors>
  <profiles>
    <profile>
      <id>nexus</id>
      <!--Enable snapshots for the built in central repo to direct -->
      <!--all requests to nexus via the mirror -->
      <repositories>
        <repository>
          <id>central</id>
          <url>http://nexus3.cpl:9081/repository/maven-public/</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
     <pluginRepositories>
        <pluginRepository>
          <id>central</id>
          <url>http://nexus3.cpl:9081/repository/maven-public/</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <activeProfiles>
    <!--make the profile active all the time -->
    <activeProfile>nexus</activeProfile>
  </activeProfiles>
</settings>
```

**Comment by fabapp2** [comment]
PluginRepositories are not adhered to in the current main branch.
You could give the revamped Parser a spin and run OpenRewrite recipes, e.g. Spring Boot Upgrade.
You find it in 'version/revamp' branch.

**Comment by InfoSec812** [comment]
The error I get is not from the plugins. 

I was able to work around it by adding a `<repositories>` block to the POM, but it would be nice if I didn't have to.
